# Generated by Django 4.2.7 on 2026-06-03 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identificador único de la cita', primary_key=True, serialize=False)),
                ('scheduled_at', models.DateTimeField(help_text='Fecha y hora programada para la entrega')),
                ('delivered_at', models.DateTimeField(blank=True, help_text="Fecha y hora real de entrega (requerido cuando estado es 'Entregada')", null=True)),
                ('status', models.CharField(choices=[('Programada', 'Programada'), ('En Proceso', 'En Proceso'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada')], db_index=True, default='Programada', help_text='Estado actual de la cita', max_length=20)),
                ('supplier', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], db_index=True, help_text='Proveedor (A, B o C)', max_length=1)),
                ('product_line', models.CharField(choices=[('Camisetas', 'Camisetas'), ('Pantalones', 'Pantalones'), ('Zapatos', 'Zapatos'), ('Accesorios', 'Accesorios')], db_index=True, help_text='Línea de producto', max_length=50)),
                ('observations', models.TextField(blank=True, help_text='Observaciones adicionales sobre la cita')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Usuario que creó la cita', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(help_text='Usuario que actualizó la cita por última vez', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['scheduled_at'], name='appointment_schedul_7069dc_idx'), models.Index(fields=['status', 'scheduled_at'], name='appointment_status_eec9f6_idx'), models.Index(fields=['supplier', 'status'], name='appointment_supplie_dbd5f1_idx'), models.Index(fields=['product_line', 'status'], name='appointment_product_f97dd0_idx')],
            },
        ),
    ]
