# Generated by Django 4.2.7 on 2026-06-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_add_report_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(
                fields=['status', 'product_line', 'scheduled_at', 'delivered_at'],
                name='appointment_report_covering_idx'
            ),
        ),
    ]
